### ISSUE TITLE
Double assignment of balance in account

### ISSUE THREAD

**Issue by tcgj** [AY1920S1-CS2103T-W13-4/main#167]
Not sure why there's assignment within the arguments here

_Originally posted by @tcgj in https://github.com/AY1920S1-CS2103T-W13-4/main/pull/157_

**Comment by kenneth-fung** [comment]
Also, I think `balance` is currently represented in the UI in cents, which is why it goes into the thousands. Might have to add the decimal.

**Comment by kenneth-fung** [comment]
Fixed.
